export declare var testPathNormalize: () => void;
export declare var testPathJoin: () => void;
export declare var testPathSeparator: () => void;
export declare var testFileFromPath: () => void;
export declare var testFolderFromPath: () => void;
export declare var testFileWrite: () => void;
export declare var testGetFile: () => void;
export declare var testGetFolder: () => void;
export declare var testFileRead: () => void;
export declare var testFileReadWriteBinary: () => void;
export declare var testGetKnownFolders: () => void;
export declare var testIOSSpecificKnownFolders: () => void;
export declare var testGetEntities: () => void;
export declare var testEnumEntities: () => void;
export declare var testGetParent: () => void;
export declare var testFileNameExtension: () => void;
export declare var testFileExists: () => void;
export declare var testFolderExists: () => void;
export declare var testContainsFile: () => void;
export declare var testFileRename: () => void;
export declare var testFolderRename: () => void;
export declare var testFileRemove: () => void;
export declare var testFolderRemove: () => void;
export declare var testFolderClear: () => void;
export declare var testKnownFolderRename: () => void;
export declare function testKnownFolderRemove(done: any): void;
export declare function test_FSEntity_Properties(): void;
export declare function test_FileSize(done: any): void;
export declare function test_UnlockAfterWrite(done: any): void;
export declare function test_CreateParentOnNewFile(done: any): void;
export declare function test_FolderClear_RemovesEmptySubfolders(done: any): void;
//# sourceMappingURL=file-system-tests.d.ts.map