export declare function test_recycling(): void;
export declare function test_set_items_to_array_loads_all_items(): void;
export declare function test_set_items_to_array_creates_views(): void;
export declare function test_refresh_after_adding_items_to_array_loads_new_items(): void;
export declare function test_refresh_reloads_all_items(): void;
export declare function test_set_itmes_to_null_clears_items(): void;
export declare function test_set_itemsLayout_accepted(): void;
export declare function test_set_itmes_to_undefiend_clears_items(): void;
export declare function test_set_itmes_to_different_source_loads_new_items(): void;
export declare function test_set_items_to_observable_array_loads_all_items(): void;
export declare function test_add_to_observable_array_refreshes_the_Repeater(): void;
export declare function test_remove_from_observable_array_refreshes_the_Repeater(): void;
export declare function test_splice_observable_array_refreshes_the_Repeater(): void;
export declare function test_usingAppLevelConvertersInRepeaterItems(): void;
export declare function test_BindingRepeaterToASimpleArray(): void;
export declare function test_ItemTemplateFactoryFunction(): void;
export declare function test_BindingRepeaterToASimpleArrayWithExpression(): void;
export declare var test_RepeaterItemsGestureBindings: () => void;
export declare var test_RepeaterItemsParentBindingsShouldWork: () => void;
export declare function test_ChildrenAreNotCreatedUntilTheRepeaterIsLoaded(): void;
//# sourceMappingURL=repeater-tests.d.ts.map