export declare function setUp(): void;
export declare function tearDown(): void;
export declare function test_custom_attribute_is_reported_in_dom_node(): void;
export declare function test_custom__falsy_attribute_is_reported_in_dom_node(): void;
export declare function test_property_is_reported_in_dom_node(): void;
export declare function test_childNodeInserted_in_dom_node(): void;
export declare function test_childNodeInserted_at_index_in_dom_node(): void;
export declare function test_childNodeRemoved_in_dom_node(): void;
export declare function test_falsy_property_is_reported_in_dom_node(): void;
export declare function test_property_change_calls_attributeModified(): void;
export declare function test_property_change_from_native_calls_attributeModified(): void;
export declare function test_property_reset_calls_attributeRemoved(): void;
export declare function test_coercible_property_change_calls_attributeModified(): void;
export declare function test_coercible_property_reset_calls_attributeRemoved(): void;
export declare function test_inspector_ui_setAttributeAsText_set_existing_property(): void;
export declare function test_inspector_ui_setAttributeAsText_remove_existing_property(): void;
export declare function test_inspector_ui_setAttributeAsText_set_new_property(): void;
export declare function test_inspector_ui_removeNode(): void;
//# sourceMappingURL=dom-node-tests.d.ts.map