export declare function pageLoaded(args: any): void;
export declare function test_recycling(): void;
export declare var testSetText: () => void;
export declare var testSetTextNull: () => void;
export declare var testSetTextUndefined: () => void;
export declare var testBindTextDirectlyToModel: () => void;
export declare var testBindTextToBindingContext: () => void;
export declare var testTextIsUpdatedWhenUserTypes: () => void;
export declare var testSetHint: () => void;
export declare var testBindHintDirectlyToModel: () => void;
export declare var testBindHintToBindingConext: () => void;
export declare var testHintPlusTextiOS: () => void;
export declare var testHintColoriOS: () => void;
export declare var testSetEditable: () => void;
export declare var testBindEditableDirectlyToModel: () => void;
export declare var testBindEditableToBindingConext: () => void;
export declare var testLocalFontSizeFromCss: () => void;
export declare var testNativeFontSizeFromCss: () => void;
export declare var testNativeFontSizeFromLocal: () => void;
export declare var testLocalLineHeightFromCss: () => void;
export declare var testLocalColorFromCss: () => void;
export declare var testNativeColorFromCss: () => void;
export declare var testNativeColorFromLocal: () => void;
export declare var testLocalBackgroundColorFromCss: () => void;
export declare var testNativeBackgroundColorFromCss: () => void;
export declare var testNativeBackgroundColorFromLocal: () => void;
export declare var testLocalTextAlignmentFromCss: () => void;
export declare var testNativeTextAlignmentFromCss: () => void;
export declare var testNativeTextAlignmentFromLocal: () => void;
export declare var testMemoryLeak: (done: any) => void;
export declare function test_watch_listerer_is_removed_at_onDetach(): void;
export declare function test_IntegrationTest_Transform_Decoration_Spacing_WithoutFormattedText_DoesNotCrash(): void;
export declare function test_IntegrationTest_Transform_Decoration_Spacing_WithFormattedText_DoesNotCrash(): void;
//# sourceMappingURL=text-view-tests.d.ts.map