import { Observable } from "../data/observable";
declare const events: Observable;
export declare function hasLaunched(): boolean;
export { Observable };
import { UnhandledErrorEventData, iOSApplication, AndroidApplication, CssChangedEventData, LoadAppCSSEventData } from ".";
export { UnhandledErrorEventData, CssChangedEventData, LoadAppCSSEventData };
export declare const launchEvent = "launch";
export declare const suspendEvent = "suspend";
export declare const displayedEvent = "displayed";
export declare const resumeEvent = "resume";
export declare const exitEvent = "exit";
export declare const lowMemoryEvent = "lowMemory";
export declare const uncaughtErrorEvent = "uncaughtError";
export declare const orientationChangedEvent = "orientationChanged";
export declare function getResources(): any;
export declare function setResources(res: any): void;
export declare let android: any;
export declare let ios: any;
export declare const on: typeof events.on;
export declare const off: typeof events.off;
export declare const notify: typeof events.notify;
export declare const hasListeners: typeof events.hasListeners;
export declare function setApplication(instance: iOSApplication | AndroidApplication): void;
export declare function livesync(): void;
export declare function setCssFileName(cssFileName: string): void;
export declare function getCssFileName(): string;
export declare function loadAppCss(): void;
export declare function addCss(cssText: string): void;
//# sourceMappingURL=application-common.d.ts.map