export declare var test_BindingExpressions_ArrayAccess: () => void;
export declare var test_BindingExpressions_LogicalOperators: () => void;
export declare var test_BindingExpressions_UnaryOperators: () => void;
export declare var test_BindingExpressions_BinaryOperators: () => void;
export declare var test_BindingExpressions_ComparisonOperators: () => void;
export declare var test_BindingExpressions_LogicalComparisonOperators: () => void;
export declare var test_BindingExpressions_TernaryOperator: () => void;
export declare var test_BindingExpressions_GroupingParenthesis: () => void;
export declare var assertElementString: (elementId: string, value: any) => void;
export declare var assertElementValueIsNaN: (elementId: string) => void;
export declare var navigateToPage: (pageName: string) => void;
//# sourceMappingURL=binding-expressions-tests.d.ts.map