export declare function test_recycling(): void;
export declare var testSetText: () => void;
export declare var testSetTextNull: () => void;
export declare var testSetTextUndefined: () => void;
export declare var testSetTextToZero: () => void;
export declare var testSetTextWithSpan: () => void;
export declare var testSetTextNullWithSpan: () => void;
export declare var testSetTextUndefinedWithSpan: () => void;
export declare var testSetTextToZeroWithSpan: () => void;
export declare var testSetHintToNumber: () => void;
export declare var testBindTextDirectlyToModel: () => void;
export declare var testBindTextToBindingContext: () => void;
export declare var testTextIsUpdatedWhenUserTypes: () => void;
export declare var testSetHint: () => void;
export declare var testBindHintDirectlyToModel: () => void;
export declare var testBindHintToBindingConext: () => void;
export declare var testSetSecure: () => void;
export declare var testSetSecureAndKeyboardTypeNumber: () => void;
export declare var testSetKeyboardTypeNumberAndSecure: () => void;
export declare var testBindSecureDirectlyToModel: () => void;
export declare var testBindSecureToBindingConext: () => void;
export declare var testLocalFontSizeFromCss: () => void;
export declare var testNativeFontSizeFromCss: () => void;
export declare var testNativeFontSizeFromLocal: () => void;
export declare var testLocalColorFromCss: () => void;
export declare var testNativeColorFromCss: () => void;
export declare var testNativeColorFromLocal: () => void;
export declare var testLocalBackgroundColorFromCss: () => void;
export declare var testNativeBackgroundColorFromCss: () => void;
export declare var testNativeBackgroundColorFromLocal: () => void;
export declare var testLocalTextAlignmentFromCss: () => void;
export declare var testNativeTextAlignmentFromCss: () => void;
export declare var testNativeTextAlignmentFromLocal: () => void;
export declare var testMemoryLeak: (done: any) => void;
export declare var test_WhenFormattedTextPropertyChanges_TextIsUpdated_TextBase: () => void;
export declare function test_IntegrationTest_Transform_Decoration_Spacing_WithoutFormattedText_DoesNotCrash(): void;
export declare function test_IntegrationTest_Transform_Decoration_Spacing_WithFormattedText_DoesNotCrash(): void;
export declare function test_set_placeholder_color(): void;
export declare function test_set_placeholder_color_when_hint_is_not_set(): void;
export declare function test_android_ime_actions_move_focus(): void;
//# sourceMappingURL=text-field-tests.d.ts.map