export declare var test_XMLHttpRequest_isDefined: () => void;
export declare var test_XMLHttpRequest_open_isDefined: () => void;
export declare var test_XMLHttpRequest_send_isDefined: () => void;
export declare var test_XMLHttpRequest_setRequestHeader_isDefined: () => void;
export declare var test_XMLHttpRequest_getAllResponseHeaders_isDefined: () => void;
export declare var test_XMLHttpRequest_getResponseHeader_isDefined: () => void;
export declare var test_XMLHttpRequest_overrideMimeType_isDefined: () => void;
export declare var test_XMLHttpRequest_readyState_isDefined: () => void;
export declare var test_XMLHttpRequest_responseText_isDefined: () => void;
export declare var test_XMLHttpRequest_responseType_isDefined: () => void;
export declare var test_XMLHttpRequest_readyStateShouldChange: (done: any) => void;
export declare var test_XMLHttpRequest_headersSentAndReceivedProperly: (done: any) => void;
export declare var test_XMLHttpRequest_setResponseTypeShouldNotThrow: (done: any) => void;
export declare var test_XMLHttpRequest_contentSentAndReceivedProperly: (done: any) => void;
export declare var test_XMLHttpRequest_FormDataContentSentAndReceivedProperly: (done: any) => void;
export declare var test_XMLHttpRequest_abortShouldCancelonreadystatechange: (done: any) => void;
export declare var test_XMLHttpRequest_requestShouldBePossibleAfterAbort: (done: any) => void;
export declare function test_ignore_zero_length_request_body(): void;
export declare function test_raises_onload_Event(done: any): void;
export declare function test_xhr_events(): void;
export declare function test_xhr_responseType_rss(): void;
export declare function test_xhr_responseType_text(): void;
export declare function test_xhr_responseType_switched_to_JSON_if_header_present(): void;
export declare function test_xhr_responseType_switched_to_JSON_if_headers_content_type_has_json_suffix(): void;
export declare function test_sets_status_and_statusText(done: any): void;
export declare function test_raises_onerror_Event(done: any): void;
export declare function test_responseType(done: any): void;
export declare function test_getResponseHeader(): void;
export declare function test_soap_content_types_recognized_as_text(): void;
//# sourceMappingURL=xhr-tests.d.ts.map