import { Page } from "tns-core-modules/ui/page";
export declare function addLabelToPage(page: Page, text?: string): void;
export declare function test_recycling(): void;
export declare function test_AfterPageLoaded_is_called_NativeInstance_is_created(): void;
export declare function test_PageLoaded_is_called_once(): void;
export declare function test_NavigateToNewPage(): void;
export declare function test_PageNavigation_EventSequence_WithTransition(): void;
export declare function test_PageNavigation_EventSequence_WithoutTransition(): void;
export declare function test_NavigateTo_WithContext(): void;
export declare function test_NavigateTo_WithBindingContext(): void;
export declare function test_FrameBackStack_WhenNavigatingForwardAndBack(): void;
export declare function test_LoadPageFromModule(): void;
export declare function test_LoadPageFromDeclarativeWithCSS(): void;
export declare function test_LoadPageFromModuleWithCSS(): void;
export declare function test_NavigateToPageCreatedWithNavigationEntry(): void;
export declare function test_cssShouldBeAppliedToAllNestedElements(): void;
export declare function test_cssShouldBeAppliedAfterChangeToAllNestedElements(): void;
export declare function test_page_backgroundColor_is_white(): void;
export declare function test_WhenPageIsLoadedFrameCurrentPageIsNotYetTheSameAsThePage(): void;
export declare function test_WhenPageIsNavigatedToFrameCurrentPageIsNowTheSameAsThePage(): void;
export declare function test_WhenInnerViewCallsCloseModal_WithArguments_ShouldPassResult(): void;
export declare function test_WhenInnerViewCallsCloseModal_WithoutArguments_ShouldWork(): void;
export declare function test_WhenInnerViewCallsCloseCallback_WithArguments_ShouldPassResult(): void;
export declare function test_WhenInnerViewCallsCloseCallback_WithoutArguments_ShouldWork(): void;
export declare function test_WhenViewBaseCallsShowModal_WithArguments_ShouldOpenModal(): void;
export declare function test_WhenViewBaseCallsShowModal_WithoutArguments_ShouldThrow(): void;
export declare function test_WhenNavigatingForwardAndBack_IsBackNavigationIsCorrect(): void;
export declare function test_WhenRootTabViewShownModallyItCanCloseModal(): void;
export declare function test_WhenPageIsNavigatedToItCanShowAnotherPageAsModal(): void;
export declare function test_WhenModalPageShownHostPageNavigationEventsShouldNotBeRaised(): void;
export declare function test_WhenModalPageShownModalNavigationToEventsShouldBeRaised(): void;
export declare function test_WhenModalFrameShownModalEventsRaisedOnRootModalFrame(): void;
export declare function test_WhenModalPageShownShowModalEventsRaisedOnRootModalPage(): void;
export declare function test_WhenModalPageShownShowModalEventsRaisedOnRootModalTabView(): void;
export declare function test_percent_width_and_height_support(): void;
export declare function test_percent_margin_support(): void;
//# sourceMappingURL=page-tests-common.d.ts.map